FROM php:8.2-cli

# Install system deps + libraries for PHP extensions
RUN apt-get update && apt-get install -y unzip git libpng-dev libjpeg-dev libfreetype6-dev libzip-dev && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_mysql gd zip

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app
