-- Voximplant Accounts: shared credentials
CREATE TABLE IF NOT EXISTS voximplant_accounts (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name            VARCHAR(150) NOT NULL,
    account_id      VARCHAR(255) NOT NULL,
    api_key         VARCHAR(255) NOT NULL,
    is_active       TINYINT(1)   NOT NULL DEFAULT 1,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Restructure broker_routes: remove inline credentials, reference voximplant_accounts
ALTER TABLE broker_routes
    ADD COLUMN voximplant_account_ref INT UNSIGNED DEFAULT NULL AFTER country_id,
    ADD FOREIGN KEY (voximplant_account_ref) REFERENCES voximplant_accounts(id) ON DELETE SET NULL;

ALTER TABLE broker_routes
    DROP COLUMN voximplant_account_id,
    DROP COLUMN voximplant_api_key,
    DROP COLUMN caller_id;

-- Rename for clarity
ALTER TABLE broker_routes
    CHANGE COLUMN voximplant_account_ref voximplant_account_id INT UNSIGNED DEFAULT NULL;

-- Seed all countries
INSERT IGNORE INTO countries (code, name, phone_prefix, language_code, timezone) VALUES
('AF', 'Afghanistan', '+93', 'fa', 'Asia/Kabul'),
('AL', 'Albania', '+355', 'sq', 'Europe/Tirane'),
('DZ', 'Algeria', '+213', 'ar', 'Africa/Algiers'),
('AD', 'Andorra', '+376', 'ca', 'Europe/Andorra'),
('AO', 'Angola', '+244', 'pt', 'Africa/Luanda'),
('AG', 'Antigua and Barbuda', '+1268', 'en', 'America/Antigua'),
('AR', 'Argentina', '+54', 'es', 'America/Buenos_Aires'),
('AM', 'Armenia', '+374', 'hy', 'Asia/Yerevan'),
('AU', 'Australia', '+61', 'en', 'Australia/Sydney'),
('AT', 'Austria', '+43', 'de', 'Europe/Vienna'),
('AZ', 'Azerbaijan', '+994', 'az', 'Asia/Baku'),
('BS', 'Bahamas', '+1242', 'en', 'America/Nassau'),
('BH', 'Bahrain', '+973', 'ar', 'Asia/Bahrain'),
('BD', 'Bangladesh', '+880', 'bn', 'Asia/Dhaka'),
('BB', 'Barbados', '+1246', 'en', 'America/Barbados'),
('BY', 'Belarus', '+375', 'be', 'Europe/Minsk'),
('BE', 'Belgium', '+32', 'nl', 'Europe/Brussels'),
('BZ', 'Belize', '+501', 'en', 'America/Belize'),
('BJ', 'Benin', '+229', 'fr', 'Africa/Porto-Novo'),
('BT', 'Bhutan', '+975', 'dz', 'Asia/Thimphu'),
('BO', 'Bolivia', '+591', 'es', 'America/La_Paz'),
('BA', 'Bosnia and Herzegovina', '+387', 'bs', 'Europe/Sarajevo'),
('BW', 'Botswana', '+267', 'en', 'Africa/Gaborone'),
('BR', 'Brazil', '+55', 'pt', 'America/Sao_Paulo'),
('BN', 'Brunei', '+673', 'ms', 'Asia/Brunei'),
('BG', 'Bulgaria', '+359', 'bg', 'Europe/Sofia'),
('BF', 'Burkina Faso', '+226', 'fr', 'Africa/Ouagadougou'),
('BI', 'Burundi', '+257', 'fr', 'Africa/Bujumbura'),
('KH', 'Cambodia', '+855', 'km', 'Asia/Phnom_Penh'),
('CM', 'Cameroon', '+237', 'fr', 'Africa/Douala'),
('CA', 'Canada', '+1', 'en', 'America/Toronto'),
('CV', 'Cape Verde', '+238', 'pt', 'Atlantic/Cape_Verde'),
('CF', 'Central African Republic', '+236', 'fr', 'Africa/Bangui'),
('TD', 'Chad', '+235', 'fr', 'Africa/Ndjamena'),
('CL', 'Chile', '+56', 'es', 'America/Santiago'),
('CN', 'China', '+86', 'zh', 'Asia/Shanghai'),
('CO', 'Colombia', '+57', 'es', 'America/Bogota'),
('KM', 'Comoros', '+269', 'fr', 'Indian/Comoro'),
('CD', 'Congo (DRC)', '+243', 'fr', 'Africa/Kinshasa'),
('CG', 'Congo (Republic)', '+242', 'fr', 'Africa/Brazzaville'),
('CR', 'Costa Rica', '+506', 'es', 'America/Costa_Rica'),
('CI', 'Cote d\'Ivoire', '+225', 'fr', 'Africa/Abidjan'),
('HR', 'Croatia', '+385', 'hr', 'Europe/Zagreb'),
('CU', 'Cuba', '+53', 'es', 'America/Havana'),
('CY', 'Cyprus', '+357', 'el', 'Asia/Nicosia'),
('CZ', 'Czech Republic', '+420', 'cs', 'Europe/Prague'),
('DK', 'Denmark', '+45', 'da', 'Europe/Copenhagen'),
('DJ', 'Djibouti', '+253', 'fr', 'Africa/Djibouti'),
('DM', 'Dominica', '+1767', 'en', 'America/Dominica'),
('DO', 'Dominican Republic', '+1809', 'es', 'America/Santo_Domingo'),
('EC', 'Ecuador', '+593', 'es', 'America/Guayaquil'),
('EG', 'Egypt', '+20', 'ar', 'Africa/Cairo'),
('SV', 'El Salvador', '+503', 'es', 'America/El_Salvador'),
('GQ', 'Equatorial Guinea', '+240', 'es', 'Africa/Malabo'),
('ER', 'Eritrea', '+291', 'ti', 'Africa/Asmara'),
('EE', 'Estonia', '+372', 'et', 'Europe/Tallinn'),
('SZ', 'Eswatini', '+268', 'en', 'Africa/Mbabane'),
('ET', 'Ethiopia', '+251', 'am', 'Africa/Addis_Ababa'),
('FJ', 'Fiji', '+679', 'en', 'Pacific/Fiji'),
('FI', 'Finland', '+358', 'fi', 'Europe/Helsinki'),
('FR', 'France', '+33', 'fr', 'Europe/Paris'),
('GA', 'Gabon', '+241', 'fr', 'Africa/Libreville'),
('GM', 'Gambia', '+220', 'en', 'Africa/Banjul'),
('GE', 'Georgia', '+995', 'ka', 'Asia/Tbilisi'),
('DE', 'Germany', '+49', 'de', 'Europe/Berlin'),
('GH', 'Ghana', '+233', 'en', 'Africa/Accra'),
('GR', 'Greece', '+30', 'el', 'Europe/Athens'),
('GD', 'Grenada', '+1473', 'en', 'America/Grenada'),
('GT', 'Guatemala', '+502', 'es', 'America/Guatemala'),
('GN', 'Guinea', '+224', 'fr', 'Africa/Conakry'),
('GW', 'Guinea-Bissau', '+245', 'pt', 'Africa/Bissau'),
('GY', 'Guyana', '+592', 'en', 'America/Guyana'),
('HT', 'Haiti', '+509', 'fr', 'America/Port-au-Prince'),
('HN', 'Honduras', '+504', 'es', 'America/Tegucigalpa'),
('HU', 'Hungary', '+36', 'hu', 'Europe/Budapest'),
('IS', 'Iceland', '+354', 'is', 'Atlantic/Reykjavik'),
('IN', 'India', '+91', 'hi', 'Asia/Kolkata'),
('ID', 'Indonesia', '+62', 'id', 'Asia/Jakarta'),
('IR', 'Iran', '+98', 'fa', 'Asia/Tehran'),
('IQ', 'Iraq', '+964', 'ar', 'Asia/Baghdad'),
('IE', 'Ireland', '+353', 'en', 'Europe/Dublin'),
('IL', 'Israel', '+972', 'he', 'Asia/Jerusalem'),
('IT', 'Italy', '+39', 'it', 'Europe/Rome'),
('JM', 'Jamaica', '+1876', 'en', 'America/Jamaica'),
('JP', 'Japan', '+81', 'ja', 'Asia/Tokyo'),
('JO', 'Jordan', '+962', 'ar', 'Asia/Amman'),
('KZ', 'Kazakhstan', '+7', 'kk', 'Asia/Almaty'),
('KE', 'Kenya', '+254', 'sw', 'Africa/Nairobi'),
('KI', 'Kiribati', '+686', 'en', 'Pacific/Tarawa'),
('KW', 'Kuwait', '+965', 'ar', 'Asia/Kuwait'),
('KG', 'Kyrgyzstan', '+996', 'ky', 'Asia/Bishkek'),
('LA', 'Laos', '+856', 'lo', 'Asia/Vientiane'),
('LV', 'Latvia', '+371', 'lv', 'Europe/Riga'),
('LB', 'Lebanon', '+961', 'ar', 'Asia/Beirut'),
('LS', 'Lesotho', '+266', 'en', 'Africa/Maseru'),
('LR', 'Liberia', '+231', 'en', 'Africa/Monrovia'),
('LY', 'Libya', '+218', 'ar', 'Africa/Tripoli'),
('LI', 'Liechtenstein', '+423', 'de', 'Europe/Vaduz'),
('LT', 'Lithuania', '+370', 'lt', 'Europe/Vilnius'),
('LU', 'Luxembourg', '+352', 'fr', 'Europe/Luxembourg'),
('MG', 'Madagascar', '+261', 'mg', 'Indian/Antananarivo'),
('MW', 'Malawi', '+265', 'en', 'Africa/Lilongwe'),
('MY', 'Malaysia', '+60', 'ms', 'Asia/Kuala_Lumpur'),
('MV', 'Maldives', '+960', 'dv', 'Indian/Maldives'),
('ML', 'Mali', '+223', 'fr', 'Africa/Bamako'),
('MT', 'Malta', '+356', 'mt', 'Europe/Malta'),
('MH', 'Marshall Islands', '+692', 'en', 'Pacific/Majuro'),
('MR', 'Mauritania', '+222', 'ar', 'Africa/Nouakchott'),
('MU', 'Mauritius', '+230', 'en', 'Indian/Mauritius'),
('MX', 'Mexico', '+52', 'es', 'America/Mexico_City'),
('FM', 'Micronesia', '+691', 'en', 'Pacific/Pohnpei'),
('MD', 'Moldova', '+373', 'ro', 'Europe/Chisinau'),
('MC', 'Monaco', '+377', 'fr', 'Europe/Monaco'),
('MN', 'Mongolia', '+976', 'mn', 'Asia/Ulaanbaatar'),
('ME', 'Montenegro', '+382', 'sr', 'Europe/Podgorica'),
('MA', 'Morocco', '+212', 'ar', 'Africa/Casablanca'),
('MZ', 'Mozambique', '+258', 'pt', 'Africa/Maputo'),
('MM', 'Myanmar', '+95', 'my', 'Asia/Yangon'),
('NA', 'Namibia', '+264', 'en', 'Africa/Windhoek'),
('NR', 'Nauru', '+674', 'en', 'Pacific/Nauru'),
('NP', 'Nepal', '+977', 'ne', 'Asia/Kathmandu'),
('NL', 'Netherlands', '+31', 'nl', 'Europe/Amsterdam'),
('NZ', 'New Zealand', '+64', 'en', 'Pacific/Auckland'),
('NI', 'Nicaragua', '+505', 'es', 'America/Managua'),
('NE', 'Niger', '+227', 'fr', 'Africa/Niamey'),
('NG', 'Nigeria', '+234', 'en', 'Africa/Lagos'),
('KP', 'North Korea', '+850', 'ko', 'Asia/Pyongyang'),
('MK', 'North Macedonia', '+389', 'mk', 'Europe/Skopje'),
('NO', 'Norway', '+47', 'no', 'Europe/Oslo'),
('OM', 'Oman', '+968', 'ar', 'Asia/Muscat'),
('PK', 'Pakistan', '+92', 'ur', 'Asia/Karachi'),
('PW', 'Palau', '+680', 'en', 'Pacific/Palau'),
('PS', 'Palestine', '+970', 'ar', 'Asia/Gaza'),
('PA', 'Panama', '+507', 'es', 'America/Panama'),
('PG', 'Papua New Guinea', '+675', 'en', 'Pacific/Port_Moresby'),
('PY', 'Paraguay', '+595', 'es', 'America/Asuncion'),
('PE', 'Peru', '+51', 'es', 'America/Lima'),
('PH', 'Philippines', '+63', 'tl', 'Asia/Manila'),
('PL', 'Poland', '+48', 'pl', 'Europe/Warsaw'),
('PT', 'Portugal', '+351', 'pt', 'Europe/Lisbon'),
('QA', 'Qatar', '+974', 'ar', 'Asia/Qatar'),
('RO', 'Romania', '+40', 'ro', 'Europe/Bucharest'),
('RU', 'Russia', '+7', 'ru', 'Europe/Moscow'),
('RW', 'Rwanda', '+250', 'rw', 'Africa/Kigali'),
('KN', 'Saint Kitts and Nevis', '+1869', 'en', 'America/St_Kitts'),
('LC', 'Saint Lucia', '+1758', 'en', 'America/St_Lucia'),
('VC', 'Saint Vincent and the Grenadines', '+1784', 'en', 'America/St_Vincent'),
('WS', 'Samoa', '+685', 'sm', 'Pacific/Apia'),
('SM', 'San Marino', '+378', 'it', 'Europe/San_Marino'),
('ST', 'Sao Tome and Principe', '+239', 'pt', 'Africa/Sao_Tome'),
('SA', 'Saudi Arabia', '+966', 'ar', 'Asia/Riyadh'),
('SN', 'Senegal', '+221', 'fr', 'Africa/Dakar'),
('RS', 'Serbia', '+381', 'sr', 'Europe/Belgrade'),
('SC', 'Seychelles', '+248', 'fr', 'Indian/Mahe'),
('SL', 'Sierra Leone', '+232', 'en', 'Africa/Freetown'),
('SG', 'Singapore', '+65', 'en', 'Asia/Singapore'),
('SK', 'Slovakia', '+421', 'sk', 'Europe/Bratislava'),
('SI', 'Slovenia', '+386', 'sl', 'Europe/Ljubljana'),
('SB', 'Solomon Islands', '+677', 'en', 'Pacific/Guadalcanal'),
('SO', 'Somalia', '+252', 'so', 'Africa/Mogadishu'),
('ZA', 'South Africa', '+27', 'en', 'Africa/Johannesburg'),
('KR', 'South Korea', '+82', 'ko', 'Asia/Seoul'),
('SS', 'South Sudan', '+211', 'en', 'Africa/Juba'),
('ES', 'Spain', '+34', 'es', 'Europe/Madrid'),
('LK', 'Sri Lanka', '+94', 'si', 'Asia/Colombo'),
('SD', 'Sudan', '+249', 'ar', 'Africa/Khartoum'),
('SR', 'Suriname', '+597', 'nl', 'America/Paramaribo'),
('SE', 'Sweden', '+46', 'sv', 'Europe/Stockholm'),
('CH', 'Switzerland', '+41', 'de', 'Europe/Zurich'),
('SY', 'Syria', '+963', 'ar', 'Asia/Damascus'),
('TW', 'Taiwan', '+886', 'zh', 'Asia/Taipei'),
('TJ', 'Tajikistan', '+992', 'tg', 'Asia/Dushanbe'),
('TZ', 'Tanzania', '+255', 'sw', 'Africa/Dar_es_Salaam'),
('TH', 'Thailand', '+66', 'th', 'Asia/Bangkok'),
('TL', 'Timor-Leste', '+670', 'pt', 'Asia/Dili'),
('TG', 'Togo', '+228', 'fr', 'Africa/Lome'),
('TO', 'Tonga', '+676', 'to', 'Pacific/Tongatapu'),
('TT', 'Trinidad and Tobago', '+1868', 'en', 'America/Port_of_Spain'),
('TN', 'Tunisia', '+216', 'ar', 'Africa/Tunis'),
('TR', 'Turkey', '+90', 'tr', 'Europe/Istanbul'),
('TM', 'Turkmenistan', '+993', 'tk', 'Asia/Ashgabat'),
('TV', 'Tuvalu', '+688', 'en', 'Pacific/Funafuti'),
('UG', 'Uganda', '+256', 'en', 'Africa/Kampala'),
('UA', 'Ukraine', '+380', 'uk', 'Europe/Kiev'),
('AE', 'United Arab Emirates', '+971', 'ar', 'Asia/Dubai'),
('GB', 'United Kingdom', '+44', 'en', 'Europe/London'),
('US', 'United States', '+1', 'en', 'America/New_York'),
('UY', 'Uruguay', '+598', 'es', 'America/Montevideo'),
('UZ', 'Uzbekistan', '+998', 'uz', 'Asia/Tashkent'),
('VU', 'Vanuatu', '+678', 'bi', 'Pacific/Efate'),
('VA', 'Vatican City', '+379', 'it', 'Europe/Vatican'),
('VE', 'Venezuela', '+58', 'es', 'America/Caracas'),
('VN', 'Vietnam', '+84', 'vi', 'Asia/Ho_Chi_Minh'),
('YE', 'Yemen', '+967', 'ar', 'Asia/Aden'),
('ZM', 'Zambia', '+260', 'en', 'Africa/Lusaka'),
('ZW', 'Zimbabwe', '+263', 'en', 'Africa/Harare');
