ALTER TABLE lead_attempts MODIFY COLUMN call_id VARCHAR(512) DEFAULT NULL;
ALTER TABLE call_logs MODIFY COLUMN voximplant_call_id VARCHAR(512) DEFAULT NULL;
ALTER TABLE active_calls MODIFY COLUMN voximplant_call_id VARCHAR(512) DEFAULT NULL;
